[package]
name = "rsnake"
version = "0.1.0"
authors = ["Hendrik Schawe <surt91@gmail.com>"]

[dependencies]
rand = "0.5"
clap = "2.33"
piston = "0.32.0"
pistoncore-glutin_window = "0.38.0"
piston2d-graphics = "0.21.1"
piston2d-opengl_graphics = "0.46.0"
